hh_12_path  : ''
hh_12_str   : 'handheld data (12 classes)'
hh_12_name  : 'HH12'

hh_all_path : ''
hh_all_str  : 'handheld data (100 classes)'
hh_all_name : 'HH100'

synth_path  : ''
synth_str   : 'synthetic data'
synth_name  : 'synthetic'

repo_path   : ''
repo_str    : 'Repository of this project'
repo_name   : 'repository'

raw_path    : ''
raw_str     : 'Raw datasets'
raw_name    : 'raw_data'
